### PR TITLE
pom: use GraalVM 19

### PR DESCRIPTION
**Pull request by greut**
works on my machine.

```console
[micronaut-from-scratch:18649]    classlist:   6,089.13 ms
[micronaut-from-scratch:18649]        (cap):     848.42 ms
[micronaut-from-scratch:18649]        setup:   1,942.71 ms
[micronaut-from-scratch:18649]   (typeflow):  19,951.79 ms
[micronaut-from-scratch:18649]    (objects):  29,855.81 ms
[micronaut-from-scratch:18649]   (features):   2,018.99 ms
[micronaut-from-scratch:18649]     analysis:  54,519.66 ms
[micronaut-from-scratch:18649]     (clinit):     887.27 ms
[micronaut-from-scratch:18649]     universe:   2,177.79 ms
[micronaut-from-scratch:18649]      (parse):   3,160.79 ms
[micronaut-from-scratch:18649]     (inline):   5,828.18 ms
[micronaut-from-scratch:18649]    (compile):  23,698.44 ms
[micronaut-from-scratch:18649]      compile:  34,853.96 ms
[micronaut-from-scratch:18649]        image:   3,955.43 ms
[micronaut-from-scratch:18649]        write:     606.22 ms
[micronaut-from-scratch:18649]      [total]: 104,374.40 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190420092731.buildslave.jdk8u-src-tar--b03)
OpenJDK GraalVM CE 19.0.0 (build 25.212-b03-jvmci-19-b01, mixed mode)

### CODE REVIEW

**Comment by greut** [comment]
the missing screenshot from the article. **74ms**

```console
$ target/micronaut-from-scratch
10:00:34.253 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 74ms. Server Running: http://localhost:8080
```

**Comment by greut** [comment]
even faster.

> 17:06:18.954 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 47ms. Server Running: http://localhost:8080

**Comment by nfrankel** [comment]
What's the effect of `initialize-at-build-time`?

**Comment by greut** [comment]
I do not have a faint clue, but GraalVM wants it.

```
[micronaut-from-scratch:2339]    classlist:   6,925.87 ms
[micronaut-from-scratch:2339]        (cap):   1,082.47 ms
[micronaut-from-scratch:2339]        setup:   2,247.54 ms
[micronaut-from-scratch:2339]     analysis:  29,399.78 ms
Error: Class that is marked for delaying initialization to run time got initialized during image building: reactor.core.publisher.Mono. Try marking this class for build-time initialization with --initialize-at-build-time=reactor.core.publisher.Mono
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by nfrankel** [comment]
Thanks for the feedback. I tried to Google it, but I didn't anything documentation-related. I need to check that for my understanding.

**Pull request closed without merging**
